### ISSUE TITLE
toolchain install fail

### ISSUE THREAD

**Issue by djh1997** [wendlers/atom-mbed-integration#1]
im trying to install on ubuntu 17.04 and i get toolchain install fail but can find how to change the toolchain path to manually install

**Comment by wendlers** [comment]
Was it the first time you installed mbed-integration, or was it an update which caused the problem? It would be very great if you could try the following and report the output back:

* open a shell
* navigate to your atom package dir (most likely `~/.atom/packages`)
* there navigate into `mbed-integration/resources`
* try to run the installer from there with: `python2.7 mbed-bootstrap.py test`

Most of the time when the installer was not working, it was because it was not able to create the virtual environment. Also I changed lately something there, this might be a reason here ...

However, if you like to provide your own toolchain, follow the instructions [here](https://github.com/ARMmbed/mbed-cli). After all the only thing that matters is, that `mbed`and the `arm-none-eabi-`binaries are in your path.

**Comment by wendlers** [comment]
Would you mind giving the latest git version a try?

```
cd $HOME
mkdir atom-test
export ATOM_HOME=$HOME/test
mkdir $ATOM_HOME/packages
cd $ATOM_HOME/packages
git clone https://github.com/wendlers/atom-mbed-integration mbed-integration
cd mbed-integration
apm install
atom

```

**Comment by wendlers** [comment]
Ok, it was the virtualenv module (again). I think I fixed it (for now). Tested on Ubuntu 16.04 and 17.04 and Debian 9 - worked for me. I released version 0.1.4, thus before trying to do what I described before, just update the package from within atom and see if it works for you to. I close the issue, but feel free to reopen it if you still have problems.

**Comment by djh1997** [comment]
yeah that fixed it thanks :+1:

**Comment by wendlers** [comment]
nice :-) Thanks for reporting!
